name: Go package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: |
          go get -t ..\..\pkg\consumer\
          go get -t ..\..\pkg\producer\
          go test -v ..\..\pkg\consumer\
          go test -v ..\..\pkg\producer\
